# Generated by Django 3.0.2 on 2020-02-14 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('content', models.TextField(blank=True, null=True)),
                ('footnote', models.TextField(blank=True, null=True)),
                ('volume_number', models.IntegerField(blank=True, null=True)),
                ('chapter_number', models.IntegerField(blank=True, null=True)),
                ('posted', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'article',
            },
        ),
    ]
